<a href='https://www.darshan.ac.in/'> <img src='https://www.darshan.ac.in/Content/media/DU_Logo.svg' width="250" height="300"/></a>
<pre>
<center><b><h1>ML and DL</b></center>
<center><b><h1>Lab - 6</b></center>
<center><b><h1>Kalp Viradia | 23010101299 | 31/12/2025</b></center>
<pre>

# Decision Tree Classifier

In [56]:
from sklearn.datasets import load_iris

# Import iris data set using sklearn

In [57]:
data = load_iris()

# Importing the libraries

In [58]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Divide the data into input and output

In [111]:
X = data['data']
y = data['target']

In [60]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

# Splitting the dataset into the Training set and Test set

In [112]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Fitting DecisionTreeClassifier   on dataset

In [113]:
from sklearn.tree import DecisionTreeClassifier

irisModel = DecisionTreeClassifier()
print(irisModel.fit(X_train, y_train))

DecisionTreeClassifier()

# Display Decision Tree

In [114]:
from sklearn import tree

%matplotlib qt

tree.plot_tree(irisModel)

[Text(0.3076923076923077, 0.9285714285714286, 'x[3] <= 0.8\ngini = 0.664\nsamples = 105\nvalue = [31, 37, 37]'),
 Text(0.23076923076923078, 0.7857142857142857, 'gini = 0.0\nsamples = 31\nvalue = [31, 0, 0]'),
 Text(0.2692307692307693, 0.8571428571428572, 'True  '),
 Text(0.38461538461538464, 0.7857142857142857, 'x[2] <= 4.75\ngini = 0.5\nsamples = 74\nvalue = [0, 37, 37]'),
 Text(0.34615384615384615, 0.8571428571428572, '  False'),
 Text(0.15384615384615385, 0.6428571428571429, 'x[3] <= 1.6\ngini = 0.059\nsamples = 33\nvalue = [0, 32, 1]'),
 Text(0.07692307692307693, 0.5, 'gini = 0.0\nsamples = 32\nvalue = [0, 32, 0]'),
 Text(0.23076923076923078, 0.5, 'gini = 0.0\nsamples = 1\nvalue = [0, 0, 1]'),
 Text(0.6153846153846154, 0.6428571428571429, 'x[3] <= 1.75\ngini = 0.214\nsamples = 41\nvalue = [0, 5, 36]'),
 Text(0.38461538461538464, 0.5, 'x[2] <= 4.95\ngini = 0.5\nsamples = 8\nvalue = [0, 4, 4]'),
 Text(0.3076923076923077, 0.35714285714285715, 'gini = 0.0\nsamples = 2\nvalue = [0, 2, 0]'),
 Text(0.46153846153846156, 0.35714285714285715, 'x[3] <= 1.55\ngini = 0.444\nsamples = 6\nvalue = [0, 2, 4]'),
 Text(0.38461538461538464, 0.21428571428571427, 'gini = 0.0\nsamples = 3\nvalue = [0, 0, 3]'),
 Text(0.5384615384615384, 0.21428571428571427, 'x[0] <= 6.95\ngini = 0.444\nsamples = 3\nvalue = [0, 2, 1]'),
 Text(0.46153846153846156, 0.07142857142857142, 'gini = 0.0\nsamples = 2\nvalue = [0, 2, 0]'),
 Text(0.6153846153846154, 0.07142857142857142, 'gini = 0.0\nsamples = 1\nvalue = [0, 0, 1]'),
 Text(0.8461538461538461, 0.5, 'x[2] <= 4.85\ngini = 0.059\nsamples = 33\nvalue = [0, 1, 32]'),
 Text(0.7692307692307693, 0.35714285714285715, 'x[1] <= 3.1\ngini = 0.444\nsamples = 3\nvalue = [0, 1, 2]'),
 Text(0.6923076923076923, 0.21428571428571427, 'gini = 0.0\nsamples = 2\nvalue = [0, 0, 2]'),
 Text(0.8461538461538461, 0.21428571428571427, 'gini = 0.0\nsamples = 1\nvalue = [0, 1, 0]'),
 Text(0.9230769230769231, 0.35714285714285715, 'gini = 0.0\nsamples = 30\nvalue = [0, 0, 30]')]

# Predict the x_test

In [115]:
irisModel.predict(X_test)

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0])

In [116]:
irisModel.score(X_test, y_test)

1.0

# Save Model State

In [99]:
import pickle

In [117]:
with open('iris_model.pkl', 'wb') as file:
    pickle.dump(irisModel, file)

# Load Model from Disk

In [118]:
with open('iris_model.pkl', 'rb') as file:
    loaded_iris_model = pickle.load(file)

In [119]:
loaded_iris_model.predict(X_test)

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0, 0, 0, 1, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 0,
       0])

# Import diabetes.csv dataset

In [67]:
df = pd.read_csv('diabetes.csv')

In [68]:
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,Diabetic
1,1,85,66,29,0,26.6,0.351,31,Non Diabetic
2,8,183,64,0,0,23.3,0.672,32,Diabetic
3,1,89,66,23,94,28.1,0.167,21,Non Diabetic
4,0,137,40,35,168,43.1,2.288,33,Diabetic

# Check the distribution of the target

In [69]:
df['Outcome'].value_counts()

Outcome
Non Diabetic    500
Diabetic        268
Name: count, dtype: int64

# Replace zeros with NaN for specific columns

In [70]:
cols = ['Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI']
df[cols] = df[cols].replace(0, np.nan)

# Check for missing values

In [71]:
df.isnull().sum()

Pregnancies                   0
Glucose                       5
BloodPressure                35
SkinThickness               227
Insulin                     374
BMI                          11
DiabetesPedigreeFunction      0
Age                           0
Outcome                       0
dtype: int64

# Fill missing values with median

In [72]:
df[cols] = df[cols].fillna(df[cols].median())

# Visualize Distributions

In [90]:
sns.pairplot(df, hue='Outcome')

# Convert Target data into integer code

In [75]:
df['Outcome'] = df['Outcome'].map({'Non Diabetic': 0, 'Diabetic': 1})

In [77]:
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148.0,72.0,35.0,125.0,33.6,0.627,50,1
1,1,85.0,66.0,29.0,125.0,26.6,0.351,31,0
2,8,183.0,64.0,29.0,125.0,23.3,0.672,32,1
3,1,89.0,66.0,23.0,94.0,28.1,0.167,21,0
4,0,137.0,40.0,35.0,168.0,43.1,2.288,33,1

# Divide the data into input and output

In [120]:
X = df.iloc[::, :-1]
y = df['Outcome']

# Splitting the dataset into the Training set and Test set

In [121]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

# Create Model

In [122]:
diabetesModel = DecisionTreeClassifier()

# Fitting DecisionTreeClassifier   on dataset

In [123]:
print(diabetesModel.fit(X_train, y_train))

DecisionTreeClassifier()

# Display Decision Tree

In [124]:
tree.plot_tree(diabetesModel)

[Text(0.5650206560863874, 0.9666666666666667, 'x[1] <= 154.5\ngini = 0.455\nsamples = 537\nvalue = [349, 188]'),
 Text(0.22428214986910994, 0.9, 'x[7] <= 28.5\ngini = 0.383\nsamples = 454\nvalue = [337, 117]'),
 Text(0.3946514029777487, 0.9333333333333333, 'True  '),
 Text(0.10471204188481675, 0.8333333333333334, 'x[1] <= 127.5\ngini = 0.22\nsamples = 238\nvalue = [208, 30]'),
 Text(0.06282722513089005, 0.7666666666666667, 'x[5] <= 49.1\ngini = 0.117\nsamples = 192\nvalue = [180, 12]'),
 Text(0.05235602094240838, 0.7, 'x[5] <= 31.4\ngini = 0.1\nsamples = 190\nvalue = [180, 10]'),
 Text(0.031413612565445025, 0.6333333333333333, 'x[4] <= 48.5\ngini = 0.018\nsamples = 108\nvalue = [107, 1]'),
 Text(0.020942408376963352, 0.5666666666666667, 'x[6] <= 0.63\ngini = 0.142\nsamples = 13\nvalue = [12, 1]'),
 Text(0.010471204188481676, 0.5, 'gini = 0.0\nsamples = 12\nvalue = [12, 0]'),
 Text(0.031413612565445025, 0.5, 'gini = 0.0\nsamples = 1\nvalue = [0, 1]'),
 Text(0.041884816753926704, 0.5666666666666667, 'gini = 0.0\nsamples = 95\nvalue = [95, 0]'),
 Text(0.07329842931937172, 0.6333333333333333, 'x[4] <= 122.5\ngini = 0.195\nsamples = 82\nvalue = [73, 9]'),
 Text(0.06282722513089005, 0.5666666666666667, 'gini = 0.0\nsamples = 31\nvalue = [31, 0]'),
 Text(0.08376963350785341, 0.5666666666666667, 'x[6] <= 0.128\ngini = 0.291\nsamples = 51\nvalue = [42, 9]'),
 Text(0.07329842931937172, 0.5, 'gini = 0.0\nsamples = 1\nvalue = [0, 1]'),
 Text(0.09424083769633508, 0.5, 'x[6] <= 0.5\ngini = 0.269\nsamples = 50\nvalue = [42, 8]'),
 Text(0.06806282722513089, 0.43333333333333335, 'x[5] <= 33.65\ngini = 0.128\nsamples = 29\nvalue = [27, 2]'),
 Text(0.05759162303664921, 0.36666666666666664, 'x[5] <= 33.25\ngini = 0.346\nsamples = 9\nvalue = [7, 2]'),
 Text(0.04712041884816754, 0.3, 'x[2] <= 73.0\ngini = 0.219\nsamples = 8\nvalue = [7, 1]'),
 Text(0.03664921465968586, 0.23333333333333334, 'gini = 0.0\nsamples = 5\nvalue = [5, 0]'),
 Text(0.05759162303664921, 0.23333333333333334, 'x[5] <= 31.8\ngini = 0.444\nsamples = 3\nvalue = [2, 1]'),
 Text(0.04712041884816754, 0.16666666666666666, 'gini = 0.0\nsamples = 1\nvalue = [0, 1]'),
 Text(0.06806282722513089, 0.16666666666666666, 'gini = 0.0\nsamples = 2\nvalue = [2, 0]'),
 Text(0.06806282722513089, 0.3, 'gini = 0.0\nsamples = 1\nvalue = [0, 1]'),
 Text(0.07853403141361257, 0.36666666666666664, 'gini = 0.0\nsamples = 20\nvalue = [20, 0]'),
 Text(0.12041884816753927, 0.43333333333333335, 'x[6] <= 0.551\ngini = 0.408\nsamples = 21\nvalue = [15, 6]'),
 Text(0.09947643979057591, 0.36666666666666664, 'x[5] <= 41.75\ngini = 0.32\nsamples = 5\nvalue = [1, 4]'),
 Text(0.08900523560209424, 0.3, 'gini = 0.0\nsamples = 4\nvalue = [0, 4]'),
 Text(0.1099476439790576, 0.3, 'gini = 0.0\nsamples = 1\nvalue = [1, 0]'),
 Text(0.14136125654450263, 0.36666666666666664, 'x[7] <= 23.5\ngini = 0.219\nsamples = 16\nvalue = [14, 2]'),
 Text(0.13089005235602094, 0.3, 'x[6] <= 0.64\ngini = 0.5\nsamples = 4\nvalue = [2, 2]'),
 Text(0.12041884816753927, 0.23333333333333334, 'gini = 0.0\nsamples = 2\nvalue = [2, 0]'),
 Text(0.14136125654450263, 0.23333333333333334, 'gini = 0.0\nsamples = 2\nvalue = [0, 2]'),
 Text(0.1518324607329843, 0.3, 'gini = 0.0\nsamples = 12\nvalue = [12, 0]'),
 Text(0.07329842931937172, 0.7, 'gini = 0.0\nsamples = 2\nvalue = [0, 2]'),
 Text(0.14659685863874344, 0.7666666666666667, 'x[3] <= 27.5\ngini = 0.476\nsamples = 46\nvalue = [28, 18]'),
 Text(0.12041884816753927, 0.7, 'x[7] <= 24.0\ngini = 0.245\nsamples = 14\nvalue = [12, 2]'),
 Text(0.1099476439790576, 0.6333333333333333, 'gini = 0.0\nsamples = 11\nvalue = [11, 0]'),
 Text(0.13089005235602094, 0.6333333333333333, 'x[7] <= 27.5\ngini = 0.444\nsamples = 3\nvalue = [1, 2]'),
 Text(0.12041884816753927, 0.5666666666666667, 'gini = 0.0\nsamples = 2\nvalue = [0, 2]'),
 Text(0.14136125654450263, 0.5666666666666667, 'gini = 0.0\nsamples = 1\nvalue = [1, 0]'),
 Text(0.17277486910994763, 0.7, 'x[2] <= 61.0\ngini = 0.5\nsamples = 32\nvalue = [16, 16]'),
 Text(0.16230366492146597, 0.6333333333333333, 'gini = 0.0\nsamples = 4\nvalue = [0, 4]'),
 Text(0.18324607329842932, 0.6333333333333333, 'x[0] <= 0.5\ngini = 0.49\nsamples = 28\nvalue = [16, 12]'),
 Text(0.16230366492146597, 0.5666666666666667, 'x[5] <= 33.75\ngini = 0.375\nsamples = 8\nvalue = [2, 6]'),
 Text(0.1518324607329843, 0.5, 'gini = 0.0\nsamples = 2\nvalue = [2, 0]'),
 Text(0.17277486910994763, 0.5, 'gini = 0.0\nsamples = 6\nvalue = [0, 6]'),
 Text(0.20418848167539266, 0.5666666666666667, 'x[1] <= 146.5\ngini = 0.42\nsamples = 20\nvalue = [14, 6]'),
 Text(0.193717277486911, 0.5, 'x[0] <= 2.5\ngini = 0.48\nsamples = 15\nvalue = [9, 6]'),
 Text(0.17277486910994763, 0.43333333333333335, 'x[1] <= 144.5\ngini = 0.245\nsamples = 7\nvalue = [6, 1]'),
 Text(0.16230366492146597, 0.36666666666666664, 'gini = 0.0\nsamples = 6\nvalue = [6, 0]'),
 Text(0.18324607329842932, 0.36666666666666664, 'gini = 0.0\nsamples = 1\nvalue = [0, 1]'),
 Text(0.21465968586387435, 0.43333333333333335, 'x[6] <= 0.528\ngini = 0.469\nsamples = 8\nvalue = [3, 5]'),
 Text(0.20418848167539266, 0.36666666666666664, 'x[7] <= 24.5\ngini = 0.48\nsamples = 5\nvalue = [3, 2]'),
 Text(0.193717277486911, 0.3, 'gini = 0.0\nsamples = 2\nvalue = [2, 0]'),
 Text(0.21465968586387435, 0.3, 'x[6] <= 0.386\ngini = 0.444\nsamples = 3\nvalue = [1, 2]'),
 Text(0.20418848167539266, 0.23333333333333334, 'gini = 0.0\nsamples = 2\nvalue = [0, 2]'),
 Text(0.225130890052356, 0.23333333333333334, 'gini = 0.0\nsamples = 1\nvalue = [1, 0]'),
 Text(0.225130890052356, 0.36666666666666664, 'gini = 0.0\nsamples = 3\nvalue = [0, 3]'),
 Text(0.21465968586387435, 0.5, 'gini = 0.0\nsamples = 5\nvalue = [5, 0]'),
 Text(0.3438522578534031, 0.8333333333333334, 'x[5] <= 26.95\ngini = 0.481\nsamples = 216\nvalue = [129, 87]'),
 Text(0.2356020942408377, 0.7666666666666667, 'x[7] <= 29.5\ngini = 0.093\nsamples = 41\nvalue = [39, 2]'),
 Text(0.225130890052356, 0.7, 'gini = 0.0\nsamples = 1\nvalue = [0, 1]'),
 Text(0.24607329842931938, 0.7, 'x[1] <= 133.0\ngini = 0.049\nsamples = 40\nvalue = [39, 1]'),
 Text(0.2356020942408377, 0.6333333333333333, 'gini = 0.0\nsamples = 35\nvalue = [35, 0]'),
 Text(0.25654450261780104, 0.6333333333333333, 'x[0] <= 5.0\ngini = 0.32\nsamples = 5\nvalue = [4, 1]'),
 Text(0.24607329842931938, 0.5666666666666667, 'x[5] <= 22.4\ngini = 0.5\nsamples = 2\nvalue = [1, 1]'),
 Text(0.2356020942408377, 0.5, 'gini = 0.0\nsamples = 1\nvalue = [1, 0]'),
 Text(0.25654450261780104, 0.5, 'gini = 0.0\nsamples = 1\nvalue = [0, 1]'),
 Text(0.2670157068062827, 0.5666666666666667, 'gini = 0.0\nsamples = 3\nvalue = [3, 0]'),
 Text(0.4521024214659686, 0.7666666666666667, 'x[1] <= 94.5\ngini = 0.5\nsamples = 175\nvalue = [90.0, 85.0]'),
 Text(0.2879581151832461, 0.7, 'x[0] <= 9.5\ngini = 0.153\nsamples = 24\nvalue = [22, 2]'),
 Text(0.2774869109947644, 0.6333333333333333, 'gini = 0.0\nsamples = 18\nvalue = [18, 0]'),
 Text(0.29842931937172773, 0.6333333333333333, 'x[6] <= 0.291\ngini = 0.444\nsamples = 6\nvalue = [4, 2]'),
 Text(0.2879581151832461, 0.5666666666666667, 'gini = 0.0\nsamples = 3\nvalue = [3, 0]'),
 Text(0.3089005235602094, 0.5666666666666667, 'x[3] <= 36.0\ngini = 0.444\nsamples = 3\nvalue = [1, 2]'),
 Text(0.29842931937172773, 0.5, 'gini = 0.0\nsamples = 2\nvalue = [0, 2]'),
 Text(0.3193717277486911, 0.5, 'gini = 0.0\nsamples = 1\nvalue = [1, 0]'),
 Text(0.616246727748691, 0.7, 'x[6] <= 0.528\ngini = 0.495\nsamples = 151\nvalue = [68, 83]'),
 Text(0.42097513089005234, 0.6333333333333333, 'x[4] <= 109.0\ngini = 0.499\nsamples = 101\nvalue = [53, 48]'),
 Text(0.3507853403141361, 0.5666666666666667, 'x[1] <= 128.0\ngini = 0.26\nsamples = 13\nvalue = [11, 2]'),
 Text(0.3403141361256545, 0.5, 'gini = 0.0\nsamples = 10\nvalue = [10, 0]'),
 Text(0.3612565445026178, 0.5, 'x[7] <= 40.0\ngini = 0.444\nsamples = 3\nvalue = [1, 2]'),
 Text(0.3507853403141361, 0.43333333333333335, 'gini = 0.0\nsamples = 2\nvalue = [0, 2]'),
 Text(0.3717277486910995, 0.43333333333333335, 'gini = 0.0\nsamples = 1\nvalue = [1, 0]'),
 Text(0.4911649214659686, 0.5666666666666667, 'x[5] <= 28.8\ngini = 0.499\nsamples = 88\nvalue = [42, 46]'),
 Text(0.4031413612565445, 0.5, 'x[6] <= 0.251\ngini = 0.337\nsamples = 14\nvalue = [11, 3]'),
 Text(0.39267015706806285, 0.43333333333333335, 'gini = 0.0\nsamples = 8\nvalue = [8, 0]'),
 Text(0.41361256544502617, 0.43333333333333335, 'x[6] <= 0.394\ngini = 0.5\nsamples = 6\nvalue = [3, 3]'),
 Text(0.4031413612565445, 0.36666666666666664, 'gini = 0.0\nsamples = 3\nvalue = [0, 3]'),
 Text(0.42408376963350786, 0.36666666666666664, 'gini = 0.0\nsamples = 3\nvalue = [3, 0]'),
 Text(0.5791884816753927, 0.5, 'x[2] <= 83.0\ngini = 0.487\nsamples = 74\nvalue = [31.0, 43.0]'),
 Text(0.49345549738219896, 0.43333333333333335, 'x[7] <= 35.5\ngini = 0.456\nsamples = 57\nvalue = [20, 37]'),
 Text(0.44502617801047123, 0.36666666666666664, 'x[2] <= 67.0\ngini = 0.492\nsamples = 16\nvalue = [9, 7]'),
 Text(0.43455497382198954, 0.3, 'gini = 0.0\nsamples = 4\nvalue = [0, 4]'),
 Text(0.45549738219895286, 0.3, 'x[2] <= 71.0\ngini = 0.375\nsamples = 12\nvalue = [9, 3]'),
 Text(0.44502617801047123, 0.23333333333333334, 'gini = 0.0\nsamples = 6\nvalue = [6, 0]'),
 Text(0.46596858638743455, 0.23333333333333334, 'x[7] <= 33.0\ngini = 0.5\nsamples = 6\nvalue = [3, 3]'),
 Text(0.45549738219895286, 0.16666666666666666, 'x[4] <= 209.0\ngini = 0.375\nsamples = 4\nvalue = [1, 3]'),
 Text(0.44502617801047123, 0.1, 'gini = 0.0\nsamples = 3\nvalue = [0, 3]'),
 Text(0.46596858638743455, 0.1, 'gini = 0.0\nsamples = 1\nvalue = [1, 0]'),
 Text(0.47643979057591623, 0.16666666666666666, 'gini = 0.0\nsamples = 2\nvalue = [2, 0]'),
 Text(0.5418848167539267, 0.36666666666666664, 'x[1] <= 107.0\ngini = 0.393\nsamples = 41\nvalue = [11, 30]'),
 Text(0.4973821989528796, 0.3, 'x[2] <= 72.0\ngini = 0.494\nsamples = 9\nvalue = [5, 4]'),
 Text(0.4869109947643979, 0.23333333333333334, 'gini = 0.0\nsamples = 3\nvalue = [3, 0]'),
 Text(0.5078534031413613, 0.23333333333333334, 'x[3] <= 29.5\ngini = 0.444\nsamples = 6\nvalue = [2, 4]'),
 Text(0.4973821989528796, 0.16666666666666666, 'gini = 0.0\nsamples = 4\nvalue = [0, 4]'),
 Text(0.518324607329843, 0.16666666666666666, 'gini = 0.0\nsamples = 2\nvalue = [2, 0]'),
 Text(0.5863874345549738, 0.3, 'x[3] <= 28.5\ngini = 0.305\nsamples = 32\nvalue = [6, 26]'),
 Text(0.5497382198952879, 0.23333333333333334, 'x[7] <= 40.5\ngini = 0.5\nsamples = 6\nvalue = [3, 3]'),
 Text(0.5392670157068062, 0.16666666666666666, 'gini = 0.0\nsamples = 2\nvalue = [2, 0]'),
 Text(0.5602094240837696, 0.16666666666666666, 'x[6] <= 0.203\ngini = 0.375\nsamples = 4\nvalue = [1, 3]'),
 Text(0.5497382198952879, 0.1, 'gini = 0.0\nsamples = 1\nvalue = [1, 0]'),
 Text(0.5706806282722513, 0.1, 'gini = 0.0\nsamples = 3\nvalue = [0, 3]'),
 Text(0.6230366492146597, 0.23333333333333334, 'x[6] <= 0.259\ngini = 0.204\nsamples = 26\nvalue = [3, 23]'),
 Text(0.612565445026178, 0.16666666666666666, 'x[2] <= 77.0\ngini = 0.375\nsamples = 12\nvalue = [3, 9]'),
 Text(0.5916230366492147, 0.1, 'x[5] <= 32.0\ngini = 0.198\nsamples = 9\nvalue = [1, 8]'),
 Text(0.581151832460733, 0.03333333333333333, 'gini = 0.0\nsamples = 1\nvalue = [1, 0]'),
 Text(0.6020942408376964, 0.03333333333333333, 'gini = 0.0\nsamples = 8\nvalue = [0, 8]'),
 Text(0.6335078534031413, 0.1, 'x[0] <= 5.5\ngini = 0.444\nsamples = 3\nvalue = [2, 1]'),
 Text(0.6230366492146597, 0.03333333333333333, 'gini = 0.0\nsamples = 2\nvalue = [2, 0]'),
 Text(0.643979057591623, 0.03333333333333333, 'gini = 0.0\nsamples = 1\nvalue = [0, 1]'),
 Text(0.6335078534031413, 0.16666666666666666, 'gini = 0.0\nsamples = 14\nvalue = [0, 14]'),
 Text(0.6649214659685864, 0.43333333333333335, 'x[4] <= 132.5\ngini = 0.457\nsamples = 17\nvalue = [11, 6]'),
 Text(0.643979057591623, 0.36666666666666664, 'x[2] <= 95.0\ngini = 0.278\nsamples = 12\nvalue = [10, 2]'),
 Text(0.6335078534031413, 0.3, 'gini = 0.0\nsamples = 9\nvalue = [9, 0]'),
 Text(0.6544502617801047, 0.3, 'x[0] <= 9.5\ngini = 0.444\nsamples = 3\nvalue = [1, 2]'),
 Text(0.643979057591623, 0.23333333333333334, 'gini = 0.0\nsamples = 2\nvalue = [0, 2]'),
 Text(0.6649214659685864, 0.23333333333333334, 'gini = 0.0\nsamples = 1\nvalue = [1, 0]'),
 Text(0.6858638743455497, 0.36666666666666664, 'x[3] <= 19.5\ngini = 0.32\nsamples = 5\nvalue = [1, 4]'),
 Text(0.675392670157068, 0.3, 'gini = 0.0\nsamples = 1\nvalue = [1, 0]'),
 Text(0.6963350785340314, 0.3, 'gini = 0.0\nsamples = 4\nvalue = [0, 4]'),
 Text(0.8115183246073299, 0.6333333333333333, 'x[5] <= 31.6\ngini = 0.42\nsamples = 50\nvalue = [15, 35]'),
 Text(0.7696335078534031, 0.5666666666666667, 'x[5] <= 29.1\ngini = 0.498\nsamples = 17\nvalue = [9, 8]'),
 Text(0.7486910994764397, 0.5, 'x[1] <= 132.0\ngini = 0.42\nsamples = 10\nvalue = [3, 7]'),
 Text(0.7382198952879581, 0.43333333333333335, 'x[5] <= 27.35\ngini = 0.219\nsamples = 8\nvalue = [1, 7]'),
 Text(0.7277486910994765, 0.36666666666666664, 'x[7] <= 32.5\ngini = 0.5\nsamples = 2\nvalue = [1, 1]'),
 Text(0.7172774869109948, 0.3, 'gini = 0.0\nsamples = 1\nvalue = [1, 0]'),
 Text(0.7382198952879581, 0.3, 'gini = 0.0\nsamples = 1\nvalue = [0, 1]'),
 Text(0.7486910994764397, 0.36666666666666664, 'gini = 0.0\nsamples = 6\nvalue = [0, 6]'),
 Text(0.7591623036649214, 0.43333333333333335, 'gini = 0.0\nsamples = 2\nvalue = [2, 0]'),
 Text(0.7905759162303665, 0.5, 'x[7] <= 50.0\ngini = 0.245\nsamples = 7\nvalue = [6, 1]'),
 Text(0.7801047120418848, 0.43333333333333335, 'gini = 0.0\nsamples = 6\nvalue = [6, 0]'),
 Text(0.8010471204188482, 0.43333333333333335, 'gini = 0.0\nsamples = 1\nvalue = [0, 1]'),
 Text(0.8534031413612565, 0.5666666666666667, 'x[6] <= 1.149\ngini = 0.298\nsamples = 33\nvalue = [6, 27]'),
 Text(0.8324607329842932, 0.5, 'x[3] <= 54.5\ngini = 0.191\nsamples = 28\nvalue = [3, 25]'),
 Text(0.8219895287958116, 0.43333333333333335, 'x[7] <= 60.0\ngini = 0.137\nsamples = 27\nvalue = [2, 25]'),
 Text(0.8115183246073299, 0.36666666666666664, 'x[2] <= 87.0\ngini = 0.074\nsamples = 26\nvalue = [1, 25]'),
 Text(0.8010471204188482, 0.3, 'gini = 0.0\nsamples = 22\nvalue = [0, 22]'),
 Text(0.8219895287958116, 0.3, 'x[5] <= 36.65\ngini = 0.375\nsamples = 4\nvalue = [1, 3]'),
 Text(0.8115183246073299, 0.23333333333333334, 'gini = 0.0\nsamples = 3\nvalue = [0, 3]'),
 Text(0.8324607329842932, 0.23333333333333334, 'gini = 0.0\nsamples = 1\nvalue = [1, 0]'),
 Text(0.8324607329842932, 0.36666666666666664, 'gini = 0.0\nsamples = 1\nvalue = [1, 0]'),
 Text(0.8429319371727748, 0.43333333333333335, 'gini = 0.0\nsamples = 1\nvalue = [1, 0]'),
 Text(0.8743455497382199, 0.5, 'x[7] <= 36.0\ngini = 0.48\nsamples = 5\nvalue = [3, 2]'),
 Text(0.8638743455497382, 0.43333333333333335, 'gini = 0.0\nsamples = 2\nvalue = [0, 2]'),
 Text(0.8848167539267016, 0.43333333333333335, 'gini = 0.0\nsamples = 3\nvalue = [3, 0]'),
 Text(0.9057591623036649, 0.9, 'x[5] <= 28.7\ngini = 0.247\nsamples = 83\nvalue = [12, 71]'),
 Text(0.7353899091950262, 0.9333333333333333, '  False'),
 Text(0.8795811518324608, 0.8333333333333334, 'x[5] <= 25.35\ngini = 0.486\nsamples = 12\nvalue = [5, 7]'),
 Text(0.8691099476439791, 0.7666666666666667, 'gini = 0.0\nsamples = 4\nvalue = [0, 4]'),
 Text(0.8900523560209425, 0.7666666666666667, 'x[7] <= 52.5\ngini = 0.469\nsamples = 8\nvalue = [5, 3]'),
 Text(0.8795811518324608, 0.7, 'x[7] <= 25.5\ngini = 0.48\nsamples = 5\nvalue = [2, 3]'),
 Text(0.8691099476439791, 0.6333333333333333, 'gini = 0.0\nsamples = 2\nvalue = [2, 0]'),
 Text(0.8900523560209425, 0.6333333333333333, 'gini = 0.0\nsamples = 3\nvalue = [0, 3]'),
 Text(0.900523560209424, 0.7, 'gini = 0.0\nsamples = 3\nvalue = [3, 0]'),
 Text(0.9319371727748691, 0.8333333333333334, 'x[3] <= 13.5\ngini = 0.178\nsamples = 71\nvalue = [7.0, 64.0]'),
 Text(0.9214659685863874, 0.7666666666666667, 'gini = 0.0\nsamples = 1\nvalue = [1, 0]'),
 Text(0.9424083769633508, 0.7666666666666667, 'x[6] <= 1.428\ngini = 0.157\nsamples = 70\nvalue = [6, 64]'),
 Text(0.9214659685863874, 0.7, 'x[4] <= 80.0\ngini = 0.116\nsamples = 65\nvalue = [4, 61]'),
 Text(0.9109947643979057, 0.6333333333333333, 'gini = 0.0\nsamples = 1\nvalue = [1, 0]'),
 Text(0.9319371727748691, 0.6333333333333333, 'x[6] <= 0.135\ngini = 0.089\nsamples = 64\nvalue = [3, 61]'),
 Text(0.9057591623036649, 0.5666666666666667, 'x[3] <= 32.0\ngini = 0.5\nsamples = 2\nvalue = [1, 1]'),
 Text(0.8952879581151832, 0.5, 'gini = 0.0\nsamples = 1\nvalue = [0, 1]'),
 Text(0.9162303664921466, 0.5, 'gini = 0.0\nsamples = 1\nvalue = [1, 0]'),
 Text(0.9581151832460733, 0.5666666666666667, 'x[5] <= 46.8\ngini = 0.062\nsamples = 62\nvalue = [2, 60]'),
 Text(0.93717277486911, 0.5, 'x[3] <= 26.5\ngini = 0.034\nsamples = 58\nvalue = [1, 57]'),
 Text(0.9267015706806283, 0.43333333333333335, 'x[3] <= 25.5\ngini = 0.133\nsamples = 14\nvalue = [1, 13]'),
 Text(0.9162303664921466, 0.36666666666666664, 'gini = 0.0\nsamples = 11\nvalue = [0, 11]'),
 Text(0.93717277486911, 0.36666666666666664, 'x[7] <= 47.5\ngini = 0.444\nsamples = 3\nvalue = [1, 2]'),
 Text(0.9267015706806283, 0.3, 'gini = 0.0\nsamples = 2\nvalue = [0, 2]'),
 Text(0.9476439790575916, 0.3, 'gini = 0.0\nsamples = 1\nvalue = [1, 0]'),
 Text(0.9476439790575916, 0.43333333333333335, 'gini = 0.0\nsamples = 44\nvalue = [0, 44]'),
 Text(0.9790575916230366, 0.5, 'x[3] <= 39.5\ngini = 0.375\nsamples = 4\nvalue = [1, 3]'),
 Text(0.9685863874345549, 0.43333333333333335, 'gini = 0.0\nsamples = 3\nvalue = [0, 3]'),
 Text(0.9895287958115183, 0.43333333333333335, 'gini = 0.0\nsamples = 1\nvalue = [1, 0]'),
 Text(0.9633507853403142, 0.7, 'x[7] <= 28.0\ngini = 0.48\nsamples = 5\nvalue = [2, 3]'),
 Text(0.9528795811518325, 0.6333333333333333, 'gini = 0.0\nsamples = 3\nvalue = [0, 3]'),
 Text(0.9738219895287958, 0.6333333333333333, 'gini = 0.0\nsamples = 2\nvalue = [2, 0]')]

# Predict the x_test

In [125]:
diabetesModel.predict(X_test)

array([0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0], dtype=int64)

# Display Training Accuracy

In [126]:
diabetesModel.score(X_train, y_train)

1.0

# Display Test Accuracy

In [127]:
diabetesModel.score(X_test, y_test)

0.6926406926406926

# Confusion Matrix

In [128]:
from sklearn.metrics import confusion_matrix

cm  = confusion_matrix(y_test, diabetesModel.predict(X_test))

sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', 
            xticklabels=['Healthy', 'Diabetic'], 
            yticklabels=['Healthy', 'Diabetic'])
plt.ylabel('Actual')
plt.xlabel('Predicted')
plt.title('Confusion Matrix Heatmap')
plt.show()

# Save Model State

In [129]:
with open('diabetes_model.pkl', 'wb') as file:
    pickle.dump(diabetesModel, file)

# Load Model from Disk

In [130]:
with open('diabetes_model.pkl', 'rb') as file:
    loaded_diabetes_model = pickle.load(file)

In [131]:
loaded_diabetes_model.predict(X_test)

array([0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0], dtype=int64)